Breezy-Traveler/Breezy-iOS

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/API.swift
- Breezy-Traveler/Info.plist
- Breezy-Traveler/MyTripsViewController.swift
- Breezy-Traveler/NetworkingLayer.swift
- Breezy-Traveler/UserModel.swift
- Podfile
- Podfile.lock
closes #8 
GET all trips for a user now returns valid JSON object as expected.
> Network stack

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/TripModel.swift
testing that the new podfile and podfile.lock are working as expected. Needed to delete and redo pod install as those files got corrupted in creating a new branch.
> addTripModelFile

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/API.swift
- Breezy-Traveler/Base.lproj/Trips.storyboard
- Breezy-Traveler/CreateTripVC.swift
- Breezy-Traveler/MyTripsViewController.swift
- Breezy-Traveler/NetworkingLayer.swift
- Breezy-Traveler/TripDetailVC.swift
- Breezy-Traveler/TripModel.swift
- Breezy-Traveler/TripsTVCell.swift
UI able to add and delete trips from the database.
> Load trips from db

- Breezy-Traveler/API.swift
- Breezy-Traveler/AppDelegate.swift
- Breezy-Traveler/BTHotel.swift
- Breezy-Traveler/NetworkingLayer+Hotels.swift
- Breezy-Traveler/NetworkingLayer+Trips.swift
**note** in [BTHotel]() each property has been changed to `var` except for `id`
> Erick networking layer hotels

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/AlertVC.swift
- Breezy-Traveler/AppDelegate.swift
- Breezy-Traveler/LoginVC.swift
- Breezy-Traveler/NetworkingLayer+QOD.swift
- Breezy-Traveler/NetworkingLayer+Users.swift
If user inputs the wrong credentials, alertViewController pops up and lets the user know.
> Alert view controller

- Breezy-Traveler/LoginVC.swift
- Breezy-Traveler/MyTripsViewController.swift
- Breezy-Traveler/NetworkingLayer+Trips.swift
- Breezy-Traveler/PersistenceUser.swift
- Breezy-Traveler/UserModel.swift
User gets new token everytime they log in
User defaults updated with keychainSwift
> User can create trips when they arelogged in

- Breezy-Traveler/CreateTripVC.swift
- Breezy-Traveler/MyTripsViewController.swift
- Breezy-Traveler/Trips.storyboard
Username and user email updates from userDefaults
> Fixed merge conflict from MyTripsCpntroller

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/CreateTrip.storyboard
- Breezy-Traveler/LoginController+Handlers.swift
- Breezy-Traveler/Trips.storyboard
Was left over from an example from a different project. Used Firebase, not needed in this project using Moya and our own API.
> Remove unused function in Handle Register

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/AppDelegate.swift
- Breezy-Traveler/Base.lproj/Main.storyboard
- Breezy-Traveler/CreateTripVC.swift
- Breezy-Traveler/PersistenceUser.swift
- Breezy-Traveler/ProfileViewController.swift
Profile view controller allows users to pick their own profile images from their camera roll. Saves the choice using fileManager.
> Image picker user profile image

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/API.swift
- Breezy-Traveler/NetworkingLayer+Trips.swift
- Breezy-Traveler/TripDetailedViewController.swift
- Breezy-Traveler/TripDetailedViewModel.swift
- Breezy-Traveler/Trips.storyboard
- Breezy-Traveler/UtilityExensions+UIAlertController.swift
- Breezy-Traveler/UtilityExtension+UITextField.swift
- Breezy-Traveler/UtilityExtensions+Bool.swift
- Breezy-Traveler/UtilityExtensions+Date.swift
- Breezy-Traveler/UtilityExtensions+UIButton.swift
> Update Place and isPublished for a Trip

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/API.swift
- Breezy-Traveler/ExploreTripsVC.swift
- Breezy-Traveler/MyTripsViewController.swift
- Breezy-Traveler/NetworkingLayer+Trips.swift
- Breezy-Traveler/TripDetailedViewController.swift
- Breezy-Traveler/TripDetailedViewModel.swift
- Breezy-Traveler/Trips.storyboard
- Breezy-Traveler/UtilityExensions+UIAlertController.swift
- Breezy-Traveler/UtilityExtension+UITextField.swift
- Breezy-Traveler/UtilityExtensions+Bool.swift
- Breezy-Traveler/UtilityExtensions+Date.swift
- Breezy-Traveler/UtilityExtensions+UIButton.swift
- Breezy-Traveler/UtilityExtensions.swift
this how we get the last view controller of the navigation stack
```` swift
guard let lastViewController = self.navigationController?.childViewControllers[fromBack: -2] else {
fatalError("could not find second to last viewController in navigationController.childViewControllers")
}
````
> Erick unwind segue

- Breezy-Traveler/Base.lproj/Main.storyboard
- Breezy-Traveler/MyTripsViewController.swift
- Breezy-Traveler/ProfileViewController.swift
- Breezy-Traveler/Trips.storyboard
Update MyTrips View Controller with user saved profile image.
> Mini profile image  my trips view controller

- Breezy-Traveler/Base.lproj/Main.storyboard
- Breezy-Traveler/ProfileViewController.swift
- Breezy-Traveler/Trips.storyboard
closes #69  #72 
Add corner radius to make profile image appear rounded. User name is displayed above the profile image.
> Profile image circle.

- Breezy-Traveler/ImagesViewController.swift
- Breezy-Traveler/PersistenceUser.swift
- Breezy-Traveler/TripDetailedViewController.swift
- Breezy-Traveler/TripDetailedViewModel.swift
- Breezy-Traveler/TripModel.swift
- Breezy-Traveler/UICoverImageView.swift
closes #83 
Pass the fetched url from the collection of images, to the view model to update the trip property. Trip detail view shows the image. WIP:  My Trips View Controller needs to display the trip details.
> Display user selected cover image

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/Base.lproj/Main.storyboard
- Breezy-Traveler/QuoteViewController.swift
closes #71 
Change image view to stretch to fill the whole screen, quote font shrinks when the quote is too large, and the screen size shrinks.
> Auto layout quote view controller

- Breezy-Traveler/NetworkingLayer+QOD.swift
- Breezy-Traveler/QuoteViewController.swift
closes #48 
Refactored the network call to hit our API instead of the Quote of the Day API
> Quote of the day api

- Breezy-Traveler/AlertVC.swift
- Breezy-Traveler/LoginController+Handlers.swift
- Breezy-Traveler/LoginController.swift
- Breezy-Traveler/NetworkingLayer+Users.swift
- Breezy-Traveler/UtilityExtensions.swift
Add different alert views for user register and login process. If the Username or email are already stored in the database, an alert pops up. If the name field is empty a different alert pops up. If the email is not a valid email with only a single @, and a .com, or similar, an alert specific to email pops up.
Add extension in UtilitiesExtensions file for String class to check for valid email and valid password. Email check uses Regex, password only checks for length greater than 6.
> Register / Login alert view controllers

- Breezy-Traveler/ExploreTripsCollectionViewCell.swift
- Breezy-Traveler/MyTripsViewController.swift
- Breezy-Traveler/TripDetailedViewController.swift
- Breezy-Traveler/Trips.storyboard
- Breezy-Traveler/TripsTVCell.swift
> Segue to published trips from My Trips

- Breezy-Traveler/AppDelegate.swift
- Breezy-Traveler/MyTripsViewController.swift
- Breezy-Traveler/QuoteViewController.swift
- Breezy-Traveler/UtilityExtensions.swift
Update font for navigation bar on Quote and MyTrips view controllers. Using Absolute custom font from the logo.
> Font for Navigation Bar on Quotes/MyTrips

- Breezy-Traveler/TripDetailedViewController.swift
- Breezy-Traveler/TripDetailedViewModel.swift
- Breezy-Traveler/TripsDetail.storyboard
- Breezy-Traveler/UICoverImageView.swift
- Breezy-Traveler/UICoverImageView.xib
closes #98 
removes the right button and moved the like button to be the icon and not the text
> Erick refactor cover image

- Breezy-Traveler/UICoverImageView.xib
add 1:1 ratio for the like button
> Fix cover image like button

- Breezy-Traveler/Info.plist
- Breezy-Traveler/Trips.storyboard
closes #112 
Changed the value of the Initial view controller in the Project File
TODO: Add the auto login logic, mentioned here in issue #111
> Update initial view controller of the app

- Breezy-Traveler/Info.plist
- Breezy-Traveler/Trips.storyboard
> Remove toolbars from MyTripsVc

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/MyTripsViewController.swift
- Breezy-Traveler/Trips.storyboard
- Breezy-Traveler/UtilityExtensions+UIViewController.swift
closes #114 
Used 1/6 ratio for both ExploreTripCell and MyTripCell and 1/4 for the MiniProfile view
> Remove constant values from MyTrips vc

- Breezy-Traveler/LoginController.swift
closes #115 
Changed container view and button sizes based on screen height. Was hard coded values, and some elements looked poorly on the SE and iPhone 5s.
> Refactored Login/Register views sizes

- Breezy-Traveler/TripDetailedViewController.swift
>  Change UIAlert message from share trip to publish trip

- Breezy-Traveler.xcodeproj/project.pbxproj
- Breezy-Traveler/Base.lproj/Main.storyboard
- Breezy-Traveler/Info.plist
- Breezy-Traveler/LoginController.swift
- Breezy-Traveler/MyTripsViewController.swift
- Breezy-Traveler/ProfileViewController.swift
- Breezy-Traveler/TripDetailedViewController.swift
- Breezy-Traveler/Trips.storyboard
- Breezy-Traveler/UtilityExtensions+UIViewController.swift
> Profile image button

- Breezy-Traveler/Base.lproj/Main.storyboard
Feature creep. Will add this feature if users request it.
> Remove Quote of the Day view controller

- Breezy-Traveler/MyTripsViewController.swift
> Refactor auto login to MyTripsVc
